dist: trusty
sudo: required
language:
- cpp
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
script:
- gcc -v && g++ -v && cmake --version
- mkdir release
- cd release
- cmake ..
- make
- cd ..
- mkdir ipp-poly-release
- cp ./release/calc_poly ./ipp-poly-release
- cp ./README.md ./ipp-poly-release
- ls ./ipp-poly-release
- zip -r $TRAVIS_BUILD_DIR/ipp-poly.zip ./ipp-poly-release
- rm -r -f -d ./ipp-poly-release
deploy:
  provider: releases
  api_key:
    secure: aPW5bINeh5ZWSiyypsVftaTIxd/yyNYY/FV+yu+lDEPJNllJRbGyNGEea0qzFXjtYXHveiDFRy0BcexOwz8MU+JlC6M+kt8VB9r3cCLVbR/9y6nLnxSDoS9T6FQCWFXu/nCvz/ed6rXhH16vSL7SvPFxojTICsLrR6nJbkIsdMhPdcLGiyKJ+5xH0jGtXYPnZ09C9AsNFmqIfNUULS7cDW+DX/cJVw8fN4puX9dBWrafrxIs6F77re5q6EuK1XIlO7pGOzng1QEAl7hxSR2ir40+73lG5uiw3bzL6izrzmL8PcHZ4GztLEm7/vGhyosZNpRfS3yhTtU70S8Uv3SUZO5toPZq8mx80BFL9L0xqHrlIdTtoYDF+34Hxk6DZ9ixQYnQvHTiGm5TvvxzHg/HRX+8RXvixe2MKYx2ozWYJ6tfkTAfAloNUhcirB9nljqAxkndVAuxuKEW15g0f5qJE4sji0Y7dEaLW5VHg/ivOYfdmmq9/T6bgjY9oJ8DEzoGmhkU5ze5MJ0ZUOtygCxUfeyClZCLKB23QHo529wSKLRxaihsHnYenj2B7c2R/CfnZ6iaySGl67TAjjBCZjvDBhs46riuKmfF4NySoOPcitw4OGaIqbBzHaZrA8yCXeKbcUzx3xv0J7vIfCVvxJ2Hrf0FNTLdJZxiwh+Oj5ov4Sg=
  file: ipp-poly.zip
  on:
    repo: styczynski/ipp-poly
