dist: trusty

sudo: required

language:
- cpp

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    
script:
- gcc -v && g++ -v && cmake --version
- mkdir release
- cd release
- cmake ..
- make
- cd ..
- mkdir ipp-poly-release
- cp ./release/calc_poly ./ipp-poly-release
- cp ./README.md ./ipp-poly-release
- ls ./ipp-poly-release
- zip -r $TRAVIS_BUILD_DIR/ipp-poly.zip ./ipp-poly-release
- rm -r -f -d ./ipp-poly-release
- git checkout release
- git add .
- git commit -m "Prepare new release :tada:"
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git push
- git checkout release